owner: keviocastro
repo: upptime

sites:
  - name: Avus (konecty)
    url: https://avus.com.br
  - name: Foxter site (konecty)
    url: https://www.foxterciaimobiliaria.com.br/

assignees:
  - keviocastro

status-website:
  cname: upptime.solidops.cloud
  logoUrl: https://solidops.io/wp-content/themes/solidops/images/logo-header.png
  name: Solidops.io upptime
  introTitle: "**Solidops.io upptime** Esté é um monitor de saúde de aplicações web solidops.io"
  introMessage: "Esta é uma página de status de aplicações web e apis ** em tempo real **. Issues são registradas em downtimes."
