owner: keviocastro
repo: upptime

sites:
  - name: AUS (kty)
    url: https://avus.com.br
  - name: FOXTIE (kty)
    url: https://www.foxterciaimobiliaria.com.br
  - name: FOXINT (kty)
    url: https://foxter-integrations.konecty.com
  - name: FOXINT (kty)
    url: https://foxter-integrations.konecty.com
  - name: FOXCAMPIN (kty)
    url: https://foxter-activecampaign.konecty.com
  - name: FOXFLOWV2 (kty)
    url: https://foxter-flows-v2.konecty.com
  - name: FOXMAILGUN (kty)
    url: https://foxter-mailgun.konecty.com
  - name: FOXPUSH (kty)
    url: https://foxter-push.konecty.com
  - name: FOXINTEGR (kty)
    url: https://foxter-integrations.konecty.com
  - name: FOXDOWN (kty)
    url: https://foxter-downloads.konecty.com
  - name: FOXSOLINK (kty)
    url: htts://sociallink.konecty.com/facebook?hub.verify_token=$KTY_FACE_TOKEN

assignees:
  - keviocastro

status-website:
  cname: upptime.solidops.cloud
  logoUrl: https://solidops.io/wp-content/themes/solidops/images/logo-header.png
  introTitle: "**Upptime Solidops** Esté é um monitor de saúde de aplicações web e apis mantidos por solidops.io"
  name: Solidops Upptime
