owner: keviocastro
repo: upptime

sites:
  - name: AUS (kty)
    url: https://avus.com.br
  - name: FOXTIE (kty)
    url: https://www.foxterciaimobiliaria.com.br
  - name: FOXINT
    url: https://foxter-integrations.konecty.com
  - name: FOXINT
    url: https://foxter-integrations.konecty.com
  - name: FOXCAMPIN
    url: https://foxter-activecampaign.konecty.com
  - name: FOXFLOWV2
    url: https://foxter-flows-v2.konecty.com
  - name: FOXMAILGUN
    url: https://foxter-mailgun.konecty.com
  - name: FOXPUSH
    url: https://foxter-push.konecty.com
  - name: FOXINTEGR
    url: https://foxter-integrations.konecty.com
  - name: FOXDOWN
    url: https://foxter-downloads.konecty.com
  - name: FOXSOLINK
    url: https://sociallink.konecty.com

assignees:
  - keviocastro

status-website:
  cname: upptime.solidops.cloud
  logoUrl: https://solidops.io/wp-content/themes/solidops/images/logo-header.png
  introTitle: "**Upptime Solidops** Esté é um monitor de saúde de aplicações web e apis mantidos por solidops.io"
  name: Solidops Upptime
