owner: keviocastro
repo: upptime

sites:
  # (kty) FX services
  - name: FX ACTIVE CAMPAIN (kty)
    url: https://foxter-activecampaign.konecty.com
  - name: FX FLOWV2 (kty)
    url: https://foxter-flows-v2.konecty.com
  - name: FX MAILGUN (kty)
    url: https://foxter-mailgun.konecty.com
  - name: FX PUSH (kty)
    url: https://foxter-push.konecty.com
  - name: FX INTEGRATIONS (kty)
    url: https://foxter-integrations.konecty.com
  - name: FX file server (kty)
    url: https://foxter-downloads.konecty.com
  - name: FX SOCIAL LINK (kty)
    url: https://sociallink.konecty.com/facebook?hub.verify_token=$KTY_FACE_TOKEN

  # (kty) FX alpha
  - name: FX ALPHA API (kty)
    url: https://alpha-api.foxterciaimobiliaria.com.br
  - name: FX ALPHA (kty)
    url: https://alpha.foxterciaimobiliaria.com.br

  # (kty) FX backoffice
  - name: FX
    url: https://foxter-atendimento.konecty.com
  - name: FX
    url: https://rocketchat.foxter.konecty.com
  - name: FX
    url: https://ofertaativa.foxterciaimobiliaria.com.br
  - name: FX
    url: https://foxter-apps.konecty.com
  - name: FX
    url: https://foxter.konecty.com
  - name: FX
    url: https://foxter-hom.konecty.com

  # (kty) FX perdigueiro
  - name: FX
    url: https://amp.perdigueiroimoveis.com.br
  - name: FX
    url: https://perdigueiroimoveis.com.br

  # (kty) FX portal
  - name: FX portal
    url: https://festivalfoxter.com.br
  - name: FX portal
    url: https://megafestivalfoxter.com.br
  - name: FX portal
    url: https://foxterciaimobiliaria.com.br
  - name: FX portal
    url: https://foxterciaimobiliaria.com.br
  - name: FX portal api
    url: https://api.foxterciaimobiliaria.com.br
  - name: FX conteudos pages
    url: https://lancamentos.foxterciaimobiliaria.com.br
  - name: FX conteudos pages
    url: https://investimentos.foxterciaimobiliaria.com.br
  - name: FX conteudos pages
    url: https://conteudos.foxterciaimobiliaria.com.br
  - name: FX conteudos pages
    url: https://financiamento.foxterciaimobiliaria.com.br
  - name: FX corretor
    url: https://conexao.foxterciaimobiliaria.com.br
  - name: FX corretor
    url: https://corretores.foxterciaimobiliaria.com.br
  - name: FX net
    url: https://foxter.net.br
  - name: FX net
    url: https://novidadeimobiliaria.com.br
  - name: FX net
    url: https://novidadeimobiliaria.com.br

assignees:
  - keviocastro

status-website:
  cname: upptime.solidops.cloud
  logoUrl: https://solidops.io/wp-content/themes/solidops/images/logo-header.png
  introTitle: "**Upptime Solidops** Esté é um monitor de saúde de aplicações web e apis mantidos por solidops.io"
  name: Solidops Upptime
