owner: keviocastro
repo: upptime

sites:
  # (kty) FX services
  - name: FX ACTIVE CAMPAIN (kty)
    url: https://foxter-activecampaign.konecty.com
  - name: FX FLOWV2 (kty)
    url: https://foxter-flows-v2.konecty.com
  - name: FX MAILGUN (kty)
    url: https://foxter-mailgun.konecty.com
  - name: FX PUSH (kty)
    url: https://foxter-push.konecty.com
  - name: FX INTEGRATIONS (kty)
    url: https://foxter-integrations.konecty.com
  - name: FX file server (kty)
    url: https://foxter-downloads.konecty.com
  - name: FX SOCIAL LINK (kty)
    url: https://sociallink.konecty.com/facebook?hub.verify_token=$KTY_FACE_TOKEN

  # (kty) FX alpha
  - name: FX ALPHA API (kty)
    url: https://alpha-api.foxterciaimobiliaria.com.br
  - name: FX ALPHA (kty)
    url: https://alpha.foxterciaimobiliaria.com.br

  # (kty) FX backoffice
  - name: FX atendimento (kty)
    url: https://foxter-atendimento.konecty.com
  - name: FX rocket (kty)
    url: https://rocketchat.foxter.konecty.com
  - name: FX oferta (kty)
    url: https://ofertaativa.foxterciaimobiliaria.com.br
  - name: FX apps (kty)
    url: https://foxter-apps.konecty.com
  - name: FX kty (kty)
    url: https://foxter.konecty.com
  - name: FX kty hom (kty)
    url: https://foxter-hom.konecty.com

  # (kty) FX perdigueiro
  - name: FX perdigueiro amp (kty)
    url: https://amp.perdigueiroimoveis.com.br
  - name: FX perdigueiro (kty)
    url: https://perdigueiroimoveis.com.br

  # (kty) FX portal
  - name: FX portal 1 (kty)
    url: https://festivalfoxter.com.br
  - name: FX portal 2 (kty)
    url: https://megafestivalfoxter.com.br
  - name: FX portal 3 (kty)
    url: https://foxterciaimobiliaria.com.br
  - name: FX portal 4 (kty)
    url: https://foxterciaimobiliaria.com.br
  - name: FX portal api (kty)
    url: https://api.foxterciaimobiliaria.com.br
  - name: FX conteudos pages 4 (kty)
    url: https://financiamento.foxterciaimobiliaria.com.br
  - name: FX corretor (kty)
    url: https://conexao.foxterciaimobiliaria.com.br
  - name: FX corretor (kty)
    url: https://corretores.foxterciaimobiliaria.com.br
  - name: FX net (kty)
    url: https://foxter.net.br
  - name: FX net (kty)
    url: https://novidadeimobiliaria.com.br
  - name: FX net (kty)
    url: https://novidadeimobiliaria.com.br

  # (kty) AVS
  - name: AVS chat (kty)
    url: https://chat.avus.com.br
  - name: AVS integration (kty)
    url: https://avus-integrations.konecty.com
  - name: AVS  (kty)
    url: https://
  - name: AVS kty (kty)
    url: https://avus.konecty.com
  - name: AVS site kty  (kty)
    url: https://avus-site.konecty.com
  - name: AVS api  (kty)
    url: https://api.avus.com.br
  - name: AVS push api  (kty)
    url: https://push-api.avus.com.br
  - name: AVS (kty)
    url: https://avus.com.br
  - name: AVS card (kty)
    url: https://pancorretora.avus.com.br
  - name: AVS rgsp (kty)
    url: https://rgsp.avus.com.br
  - name: AVS too (kty)
    url: https://too.avus.com.br
  - name: AVS portal saude (kty)
    url: https://portaldesaude.avus.com.br
  - name: AVS app (kty)
    url: https://app.avus.com.br
  - name: AVS app avs
    url: https://app-avus.konecty.com

assignees:
  - keviocastro

status-website:
  cname: upptime.solidops.cloud
  logoUrl: https://solidops.io/wp-content/themes/solidops/images/logo-header.png
  introTitle: "**Upptime Solidops** Esté é um monitor de saúde de aplicações web e apis mantidos por [solidops.io](https://solidops.io)"
  name: "Upptime"

i18n:
  footer: This page is a [Solidops.io](https://solidops.io) page.