owner: keviocastro
repo: upptime

sites:
  - name: Avus (konecty)
    url: https://avus.com.br
  - name: Foxter site (konecty)
    url: https://www.foxterciaimobiliaria.com.br
  - name: Avus (konecty)
    url: https://avus.com.br

assignees:
  - keviocastro

status-website:
  cname: upptime.solidops.cloud
  logoUrl: https://solidops.io/wp-content/themes/solidops/images/logo-header.png
  introTitle: "**Upptime Solidops** Esté é um monitor de saúde de aplicações web e apis mantidos por solidops.io"
  name: Solidops Upptime
